[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ezopt"
version = "0.0.1"
dependencies = ["pydantic"]

[tool.hatch.build]
exclude = []

[tool.hatch.build.targets.wheel]
packages = ["ezopt/"]

[project.scripts]
ezopt = "ezopt.ezopt:main"